"""Accessible Emoji Picker data model (Insert > Emoji..., docs/planning/emo.md,
now folded into the PRD's Accessible Emoji Picker section).

QUILL never fetches emoji data at runtime (no surprise network calls; the app
must work fully offline and in Safe Mode). Instead this module loads a single
committed catalog file, ``quill/data/emoji_catalog.json``, generated offline
by :mod:`quill.tools.generate_emoji_catalog` from three tiers of source data:

1. Unicode Consortium's ``emoji-test.txt`` -- the category tree and the
   official short name for every standard emoji.
2. Unicode CLDR's English annotations -- search keywords per emoji.
3. ``iamcal/emoji-data`` (MIT) -- legacy ASCII emoticon aliases (``:)``,
   ``<3``, ...) that Unicode itself does not define.

Each entry also carries a one-to-two-sentence visual description (what the
emoji actually looks like, generated by an LLM at catalog-build time -- see
that module's docstring for why, and its own "why not scrape a picker site"
reasoning). A maintainer re-runs the generator when Unicode publishes a new
emoji version (roughly annual) and commits the regenerated catalog like any
other data update -- see the PRD's Accessible Emoji Picker section for the
full update runbook.

Pure logic, no ``wx``, strict-typed: the UI layer (``main_frame_emoji_picker.py``)
only reads the shapes here and asks :func:`describe` to render one for
display.
"""

from __future__ import annotations

import json
import threading
from dataclasses import dataclass
from pathlib import Path

from quill.core.char_describe import CharacterDescription

_CATALOG_PATH = Path(__file__).resolve().parent.parent / "data" / "emoji_catalog.json"

_LOAD_LOCK = threading.Lock()
_ENTRIES: list[EmojiEntry] | None = None
_LOAD_ERROR: str | None = None


@dataclass(frozen=True, slots=True)
class EmojiEntry:
    """One catalog entry: a standard emoji plus everything the picker needs."""

    char: str
    name: str
    category: str
    subgroup: str
    keywords: tuple[str, ...]
    emoticons: tuple[str, ...]
    description: str


def is_available() -> bool:
    """True once the catalog has loaded (or loads successfully on demand)."""
    return bool(_load())


def load_error() -> str | None:
    """The load failure reason, if the catalog is missing or malformed."""
    _load()
    return _LOAD_ERROR


def _load() -> list[EmojiEntry]:
    global _ENTRIES, _LOAD_ERROR
    with _LOAD_LOCK:
        if _ENTRIES is not None:
            return _ENTRIES
        try:
            raw = json.loads(_CATALOG_PATH.read_text(encoding="utf-8"))
            entries = [
                EmojiEntry(
                    char=item["char"],
                    name=item["name"],
                    category=item["category"],
                    subgroup=item["subgroup"],
                    keywords=tuple(item.get("keywords") or ()),
                    emoticons=tuple(item.get("emoticons") or ()),
                    description=item.get("description", ""),
                )
                for item in raw.get("entries", [])
            ]
        except Exception as exc:  # noqa: BLE001 - any load failure degrades to "empty"
            _LOAD_ERROR = str(exc)
            _ENTRIES = []
            return _ENTRIES
        _LOAD_ERROR = None
        _ENTRIES = entries
        return _ENTRIES


def list_categories() -> list[str]:
    """Unicode's category names, in the catalog's own (canonical) order."""
    seen: dict[str, None] = {}
    for entry in _load():
        seen.setdefault(entry.category, None)
    return list(seen)


def list_by_category(category: str) -> list[EmojiEntry]:
    return [e for e in _load() if e.category == category]


def entry_by_char(char: str) -> EmojiEntry | None:
    """The catalog entry for *char*, or ``None`` -- resolves a bare character
    (as stored by :mod:`quill.core.emoji_usage`'s recent/favorites lists)
    back into its full entry for display."""
    for entry in _load():
        if entry.char == char:
            return entry
    return None


def entries_by_chars(chars: list[str]) -> list[EmojiEntry]:
    """Resolve a list of characters to entries, in the same order, silently
    dropping any that no longer exist in the current catalog (a stale
    favorite/recent entry from a prior catalog version, say)."""
    out = []
    for char in chars:
        entry = entry_by_char(char)
        if entry is not None:
            out.append(entry)
    return out


def _is_emoji_like(query: str) -> bool:
    """True when *query* looks like a pasted/typed emoji rather than typed text
    (a lone ASCII/space string is never itself a catalog character)."""
    return bool(query) and any(ord(ch) > 0x2000 for ch in query)


def search(query: str) -> list[EmojiEntry]:
    """Ranked matches for *query*, best first, searching every field the
    catalog carries -- so someone can find an emoji by typing its symbol, a
    legacy emoticon, its name, a loose keyword, or even a phrase that only
    appears in its rich description ("melting" finds the melting face even
    though "melting" is not one of its CLDR keywords).

    Match order, most-confident first:

    1. *query* is itself one or more emoji characters someone pasted or typed
       in -- a direct catalog lookup by symbol.
    2. Exact match against a legacy ASCII emoticon alias (``:)``, ``<3``,
       ``:-D``, ...) -- the case someone types a smiley and expects the real
       emoji it stands in for.
    3. Substring match against the official Unicode name or a CLDR keyword.
    4. Substring match against the generated rich description -- the widest,
       lowest-precision net, for a half-remembered phrase that names neither
       the emoji nor one of its keywords.

    Each tier is deduplicated against entries already matched by an earlier,
    higher-priority tier, so a result never appears twice and stronger matches
    always sort first. An empty or all-whitespace query returns no results
    (the caller shows the category browser instead).
    """
    q = query.strip()
    if not q:
        return []
    entries = _load()
    results: list[EmojiEntry] = []
    seen_chars: set[str] = set()

    if _is_emoji_like(q):
        for entry in entries:
            if entry.char in q and entry.char not in seen_chars:
                results.append(entry)
                seen_chars.add(entry.char)

    for entry in entries:
        if entry.char in seen_chars:
            continue
        if q in entry.emoticons:
            results.append(entry)
            seen_chars.add(entry.char)

    q_lower = q.lower()
    for entry in entries:
        if entry.char in seen_chars:
            continue
        if q_lower in entry.name.lower() or any(q_lower in kw.lower() for kw in entry.keywords):
            results.append(entry)
            seen_chars.add(entry.char)

    for entry in entries:
        if entry.char in seen_chars:
            continue
        if q_lower in entry.description.lower():
            results.append(entry)
            seen_chars.add(entry.char)

    return results


def describe(entry: EmojiEntry) -> CharacterDescription:
    """A one-line summary plus the rich detail block for the picker's
    description pane -- same shape as :func:`quill.core.char_describe.describe_character`,
    so the UI already knows how to render/announce it."""
    summary = f"{entry.char} {entry.name}"
    lines = [
        f"Category: {entry.category} > {entry.subgroup}",
        f"Name: {entry.name}",
    ]
    if entry.keywords:
        lines.append("Keywords: " + ", ".join(entry.keywords))
    if entry.emoticons:
        lines.append("Also typed as: " + ", ".join(entry.emoticons))
    lines.append("")
    lines.append(entry.description)
    return CharacterDescription(summary=summary, detail="\n".join(lines))


__all__ = [
    "EmojiEntry",
    "describe",
    "entries_by_chars",
    "entry_by_char",
    "is_available",
    "list_by_category",
    "list_categories",
    "load_error",
    "search",
]
