# Generated by Copilot
"""Configuration settings for the Pronunciation Helper application.

This module contains all configuration settings including Azure Speech Service credentials,
UI settings, speech parameters, and file paths.
"""

import os

# Azure Speech Service Configuration
SPEECH_KEY = os.getenv("GITHUB_SECRET_AZURE_API_KEY", os.getenv("AZURE_API_KEY", "YOUR_DEFAULT_KEY_HERE"))
SPEECH_REGION = "westus"

# UI Configuration
WINDOW_MIN_SIZE = (400, 600)

# Speech Configuration
DEFAULT_RATE = 100  # 1.0x
DEFAULT_PITCH = 0   # 0%
DEFAULT_VOLUME = 100  # 100%
RATE_RANGE = (50, 200)  # 0.5x to 2.0x
PITCH_RANGE = (-50, 50)  # -50% to +50%
VOLUME_RANGE = (0, 100)  # 0% to 100%

# Default Speaking Options
DEFAULT_EMPHASIS_LEVELS = ['Default', 'Strong', 'Moderate', 'Reduced']

# File Configuration
SAVE_FILENAME = "pronunciation_pairs.json"

# Accessibility Configuration
TOOLTIP_BACKGROUND_COLOR = '#FFFFE0'  # Light yellow
TOOLTIP_OFFSET = (0, 20)  # Offset from control
