"""
acb_audio_pipeline_azure_cli.py

Main Azure TTS audio pipeline CLI for ACB. Handles TTS synthesis, audio processing, merging, and chapter embedding.
Refactored to use Typer for CLI argument parsing. Strictly conforms to WCAG 2.2 Level AA for accessibility (help text, keyboard navigation, screen reader compatibility).
Generated by Copilot
"""

import typer
from pathlib import Path
import logging
import azure.cognitiveservices.speech as speechsdk
from docx import Document
from docx.opc.exceptions import PackageNotFoundError
from pydub import AudioSegment
import random
import requests
import json
import subprocess
import shutil
from ssml_preprocessor import SSMLPreprocessor
from config import (
    AZURE_API_KEY,  # Azure Speech API key
    AZURE_REGION,  # Azure region for TTS
    OUTPUT_DIR,  # Output directory for all generated files
    AZURE_TRANSLATOR_KEY,  # Azure Translator API key
    AZURE_TRANSLATOR_ENDPOINT,  # Translator endpoint
    AZURE_TRANSLATOR_REGION,  # Translator region
    ENGLISH_DIR,  # Output directory for English
    SPANISH_DIR,  # Output directory for Spanish
    AZURE_NEURAL_VOICES_EN_US,  # List of English neural voices
    AZURE_NEURAL_VOICES_ES_LATAM,  # List of Spanish neural voices
    DEFAULT_STYLE,  # Default speaking style
    LANGUAGES,  # Supported languages and their configs
    DEFAULT_LANGUAGES,  # Default language order
    LOUDNORM_PARAMS,  # Parameters for loudness normalization
    TRANSLATION_MAX_RETRIES,  # Max retries for translation
    TRANSLATION_RETRY_BACKOFF_BASE,  # Base backoff time for retries
    TRANSLATION_RETRY_BACKOFF_MAX,  # Max backoff time for retries
    TRANSLATION_TIMEOUT,  # Timeout for translation requests
    BLACKLISTED_TTS_VOICES,  # Persistently blacklisted TTS voices
)

# Typer CLI app with accessibility-focused help text
app = typer.Typer(
    help="Azure TTS audio pipeline CLI. Accessible, modern, and type-safe."
)


def chunk_text(text, max_len=4500):
    """Chunk text at sentence or paragraph boundaries, not exceeding max_len per chunk.
    Ensures TTS API limits are respected and splits at natural points for accessibility.
    Generated by Copilot
    """
    import re

    paragraphs = [p.strip() for p in text.split("\n") if p.strip()]
    chunks = []
    current = ""
    for para in paragraphs:
        # If adding this paragraph would exceed max_len, flush current chunk
        if len(current) + len(para) + 1 > max_len:
            if current:
                chunks.append(current.strip())
                current = ""
        # If paragraph itself is too long, split by sentence
        if len(para) > max_len:
            sentences = re.split(r"(?<=[.!?]) +", para)
            for sent in sentences:
                if len(current) + len(sent) + 1 > max_len:
                    if current:
                        chunks.append(current.strip())
                        current = ""
                current += sent + " "
        else:
            current += para + "\n"
    if current:
        chunks.append(current.strip())
    return chunks


def synthesize_audio(ssml, speech_config, article_voice):
    """Helper function for TTS synthesis. Returns an audio segment.
    Uses Azure Speech SDK to synthesize SSML to a temporary WAV file, loads with pydub.
    Handles errors and cleans up temp files for accessibility and reliability.
    """
    import tempfile, os

    tmp_wav = tempfile.NamedTemporaryFile(suffix=".wav", delete=False)
    try:
        tmp_wav.close()
        audio_config = speechsdk.audio.AudioOutputConfig(filename=tmp_wav.name)
        synthesizer = speechsdk.SpeechSynthesizer(
            speech_config=speech_config, audio_config=audio_config
        )
        result = synthesizer.speak_ssml_async(ssml).get()
        if result.reason == speechsdk.ResultReason.SynthesizingAudioCompleted:
            audio_segment = AudioSegment.from_file(tmp_wav.name, format="wav")
            return audio_segment
        else:
            logging.error(
                "TTS synthesis failed for voice %s: %s", article_voice, result.reason
            )
            return None
    finally:
        import gc

        gc.collect()  # Help ensure file handles are released
        for _ in range(3):  # Retry unlink up to 3 times
            try:
                os.unlink(tmp_wav.name)
                break
            except PermissionError as e:
                logging.warning(
                    "Could not delete temp file %s (retrying): %s", tmp_wav.name, e
                )
                time.sleep(0.2)
            except OSError as e:
                logging.warning("Could not delete temp file %s: %s", tmp_wav.name, e)
                break


# --- Robust translation logic with hard fail on error, no fallback to English or original text ---
import time


def translate_text(text, to_lang):
    """Translate text to the target language with retry, exponential backoff. If translation fails, halt processing for this language.
    Logs all attempts and notifies user on persistent failure. Strictly WCAG 2.2 accessible.
    Generated by Copilot
    """
    if not text.strip():
        return text
    endpoint = AZURE_TRANSLATOR_ENDPOINT + "/translate?api-version=3.0"
    params = f"&from=en&to={to_lang}"
    headers = {
        "Ocp-Apim-Subscription-Key": AZURE_TRANSLATOR_KEY,
        "Ocp-Apim-Subscription-Region": AZURE_TRANSLATOR_REGION,
        "Content-type": "application/json",
    }
    body = [{"text": text}]
    attempt = 0
    backoff = TRANSLATION_RETRY_BACKOFF_BASE
    while attempt < TRANSLATION_MAX_RETRIES:
        try:
            response = requests.post(
                endpoint + params,
                headers=headers,
                json=body,
                timeout=TRANSLATION_TIMEOUT,
            )
            response.raise_for_status()
            result = response.json()
            if result and "translations" in result[0]:
                translated = result[0]["translations"][0]["text"]
                if translated.strip():
                    if attempt > 0:
                        logging.info(
                            "Translation for '%s' to %s succeeded after %d attempt(s).",
                            text[:40],
                            to_lang,
                            attempt + 1,
                        )
                    return translated
            logging.warning(
                "Empty translation result for '%s' to %s on attempt %d.",
                text[:40],
                to_lang,
                attempt + 1,
            )
        except requests.RequestException as e:
            logging.warning(
                "Translation attempt %d for '%s' to %s failed: %s",
                attempt + 1,
                text[:40],
                to_lang,
                e,
            )
        attempt += 1
        if attempt < TRANSLATION_MAX_RETRIES:
            sleep_time = min(backoff, TRANSLATION_RETRY_BACKOFF_MAX)
            logging.info(
                "Retrying translation for '%s' to %s in %d seconds (attempt %d/%d).",
                text[:40],
                to_lang,
                sleep_time,
                attempt + 1,
                TRANSLATION_MAX_RETRIES,
            )
            time.sleep(sleep_time)
            backoff *= 2
    # If we reach here, translation failed after all retries: halt processing for this language
    logging.error(
        "Translation failed for '%s' to %s after %d attempts. Halting processing for this language.",
        text[:40],
        to_lang,
        TRANSLATION_MAX_RETRIES,
    )
    typer.echo(
        f"Translation failed for text '{text[:40]}...' to {to_lang} after {TRANSLATION_MAX_RETRIES} attempts. Halting processing for this language.",
        err=True,
    )
    raise RuntimeError(
        f"Translation failed for text '{text[:40]}...' to {to_lang} after {TRANSLATION_MAX_RETRIES} attempts."
    )


# Main CLI entry point for the pipeline
# Accepts input DOCX or directory, style, language, log file, article selection, cue sound, and output cleaning options
# Implements robust, accessible, and maintainable TTS pipeline for multi-language, multi-article documents
# All output is grouped by document, language, and type (speech/text/merged)
@app.command()
def main(
    input_docx: Path = typer.Option(
        ...,
        "--input",
        help="Input DOCX file or directory (e.g., Sunday-SunshineGazette.docx or papers/)",
        exists=True,
        readable=True,
    ),
    style: str = typer.Option(
        None, "--style", help="Optional speaking style for the voice"
    ),
    lang: str = typer.Option(
        None,
        "--lang",
        help="Language code (e.g., en, es). If omitted, all DEFAULT_LANGUAGES are processed.",
    ),
    log: Path = typer.Option(
        "azure_tts_cli.log", "--log", help="Log file for pipeline output"
    ),
    use_articles_json: bool = typer.Option(
        False,
        "--use-articles-json",
        help="If set, use articles.json for article selection if it exists.",
    ),
    cue_sound: bool = typer.Option(
        False,
        "--cue-sound/--no-cue-sound",
        help="If set, insert a cue sound (page_turn.mp3) between articles when headings are present.",
    ),
    clean_output: bool = typer.Option(
        True,
        "--clean-output/--no-clean-output",
        help="If set, clean the output_audio directory before processing (default: True).",
    ),
) -> None:
    """Run the Azure TTS audio pipeline with the given arguments.
    Accepts either a DOCX file or a directory containing DOCX files for --input.
    Now supports multi-language output folders. (Generated by Copilot)"""
    # Clear the log file at program start for accessibility and to reduce log size
    with open(log, "w", encoding="utf-8") as f:
        pass  # Truncate the log file

    # Clean output_audio directory before processing if requested
    if clean_output and OUTPUT_DIR.exists():
        try:
            shutil.rmtree(OUTPUT_DIR)
            logging.info("Cleaned output directory: %s", OUTPUT_DIR)
        except (OSError, IOError) as e:
            logging.error("Failed to clean output directory %s: %s", OUTPUT_DIR, e)

    # Set up logging to file for accessibility and traceability
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s - %(levelname)s - %(message)s",
        handlers=[logging.FileHandler(log, encoding="utf-8")],
        force=True,
    )
    # Load articles.json if requested for selective article processing
    articles_to_process = None
    if use_articles_json:
        articles_json_path = Path("articles.json")
        if articles_json_path.exists():
            try:
                with open(articles_json_path, "r", encoding="utf-8") as f:
                    articles_to_process = json.load(f)
                logging.info("Loaded articles to process from articles.json")
            except json.JSONDecodeError as e:
                logging.error("Failed to load articles.json: %s", e)
                articles_to_process = None
    else:
        articles_to_process = None

    # Accept file or directory for input_docx
    input_paths = []
    if input_docx.is_file() and input_docx.suffix.lower() == ".docx":
        input_paths = [input_docx]
    elif input_docx.is_dir():
        input_paths = sorted([p for p in input_docx.glob("*.docx") if p.is_file()])
    else:
        logging.error(
            "--input must be a .docx file or a directory containing .docx files: %s",
            input_docx,
        )
        typer.echo(
            f"--input must be a .docx file or a directory containing .docx files: {input_docx}",
            err=True,
        )
        return

    # --- Refactor: Extract articles from DOCX only once (in English) ---
    docx_articles_map = {}  # {docx_path: [{{'title': ..., 'body': ...}}, ...]}
    for docx_path in input_paths:
        try:
            doc = Document(docx_path)
            # Extract articles by combining consecutive headings and only creating articles when body text is found
            articles = []
            pending_headings = []
            current_body = []
            for para in doc.paragraphs:
                if para.style.name.startswith("Heading"):
                    if current_body:
                        articles.append(
                            {
                                "title": " - ".join(pending_headings),
                                "body": "\n".join(current_body),
                            }
                        )
                        pending_headings = []
                        current_body = []
                    pending_headings.append(para.text.strip())
                else:
                    if para.text.strip():
                        current_body.append(para.text.strip())
            # After loop, flush any remaining article
            if pending_headings or current_body:
                articles.append(
                    {
                        "title": " - ".join(pending_headings),
                        "body": "\n".join(current_body),
                    }
                )
            # Fallback: if no headings found, treat as one article
            if not articles or all(not a["title"] for a in articles):
                full_text = "\n".join(
                    [p.text for p in doc.paragraphs if p.text.strip()]
                )
                first_line = next(
                    (p.text.strip() for p in doc.paragraphs if p.text.strip()),
                    docx_path.stem,
                )
                articles = [{"title": first_line, "body": full_text}]
                logging.info(
                    "No headings found; treating document %s as a single article with title '%s'.",
                    docx_path,
                    first_line,
                )
            # If articles_to_process is set, filter articles accordingly
            if articles_to_process:
                doc_key = str(docx_path.name)
                if (
                    doc_key in articles_to_process
                    and articles_to_process[doc_key] == "all"
                ):
                    pass  # Process all articles
                elif doc_key in articles_to_process and isinstance(
                    articles_to_process[doc_key], list
                ):
                    titles = set(articles_to_process[doc_key])
                    articles = [a for a in articles if a["title"] in titles]
                    logging.info(
                        "Filtered articles to process in %s: %s",
                        docx_path,
                        titles,
                    )
            docx_articles_map[docx_path] = articles
            # --- Save extracted articles to JSON for future reference ---
            articles_json_dir = OUTPUT_DIR / docx_path.stem
            articles_json_dir.mkdir(parents=True, exist_ok=True)
            articles_json_path = articles_json_dir / "articles.json"
            try:
                with open(articles_json_path, "w", encoding="utf-8") as f:
                    json.dump(articles, f, ensure_ascii=False, indent=2)
                logging.info(
                    "Saved extracted canonical articles for %s to %s",
                    docx_path,
                    articles_json_path,
                )
            except (OSError, IOError, ValueError) as e:
                # Only catch specific exceptions for file I/O
                logging.error(
                    "Failed to save articles.json for %s: %s",
                    docx_path,
                    e,
                )
        except PackageNotFoundError:
            logging.error("Input DOCX file not found: %s", docx_path)
            typer.echo(f"Input DOCX file not found: {docx_path}", err=True)
            continue
        except (OSError, IOError, ValueError) as e:
            # Only catch specific exceptions for docx parsing
            logging.error("Error parsing DOCX %s: %s", docx_path, e)
            typer.echo(f"Error parsing DOCX {docx_path}: {e}", err=True)
            continue

    # --- Multi-language processing loop: Use extracted English articles for all languages ---
    langs_to_process = [lang] if lang else DEFAULT_LANGUAGES
    logging.info(
        "Languages to process: %s", langs_to_process
    )  # Log languages being processed
    for lang_code in langs_to_process:
        logging.info("Processing language: %s", lang_code)  # Log each language
        if lang_code not in LANGUAGES:
            logging.error("Language '%s' is not supported. Skipping.", lang_code)
            typer.echo(f"Language '{lang_code}' is not supported. Skipping.", err=True)
            continue
        lang_cfg = LANGUAGES[lang_code]
        lang_voice = lang_cfg["voice"]  # Always use config.py voice
        lang_style = style if style else DEFAULT_STYLE
        for docx_path in input_paths:
            # Incremental processing: skip if merged output is up to date and clean_output is False
            merged_output_dir = OUTPUT_DIR / docx_path.stem / "merged" / lang_code
            merged_path = merged_output_dir / f"{docx_path.stem}_{lang_code}.mp3"
            if not clean_output and merged_path.exists():
                docx_mtime = docx_path.stat().st_mtime
                merged_mtime = merged_path.stat().st_mtime
                if merged_mtime >= docx_mtime:
                    logging.info(
                        "Skipping %s for language %s: merged output is up to date.",
                        docx_path,
                        lang_code,
                    )
                    continue
            # --- Use canonical English articles for all languages ---
            articles = []
            articles_json_path = OUTPUT_DIR / docx_path.stem / "articles.json"
            if lang_code == "en":
                # Use in-memory extraction for English
                articles = docx_articles_map.get(docx_path, [])
            else:
                # For other languages, load from articles.json if available
                if articles_json_path.exists():
                    try:
                        with open(articles_json_path, "r", encoding="utf-8") as f:
                            articles = json.load(f)
                        logging.info(
                            "Loaded canonical articles for translation from %s",
                            articles_json_path,
                        )
                    except (OSError, IOError, json.JSONDecodeError) as e:
                        logging.error(
                            "Failed to load articles.json for %s: %s. Falling back to in-memory extraction.",
                            docx_path,
                            e,
                        )
                        articles = docx_articles_map.get(docx_path, [])
                else:
                    articles = docx_articles_map.get(docx_path, [])
            # Voice selection logic for multiple headings
            voices_to_use = []
            if len(articles) > 1:
                if lang_code == "en":
                    voice_list = [
                        v
                        for v in AZURE_NEURAL_VOICES_EN_US
                        if v not in BLACKLISTED_TTS_VOICES
                    ]
                elif lang_code == "es":
                    voice_list = [
                        v
                        for v in AZURE_NEURAL_VOICES_ES_LATAM
                        if v not in BLACKLISTED_TTS_VOICES
                    ]
                else:
                    voice_list = (
                        [lang_voice] if lang_voice not in BLACKLISTED_TTS_VOICES else []
                    )
                random.shuffle(voice_list)
                # Assign voices to articles in a round-robin, but rotate for each article for max variety
                voices_to_use = []
                for i in range(len(articles)):
                    # Rotate the voice list for each article to maximize variety
                    rotated = (
                        voice_list[i % len(voice_list) :]
                        + voice_list[: i % len(voice_list)]
                        if voice_list
                        else []
                    )
                    voices_to_use.append(rotated[0] if rotated else lang_voice)
            else:
                voices_to_use = (
                    [lang_voice] * len(articles)
                    if lang_voice not in BLACKLISTED_TTS_VOICES
                    else []
                )
            for article_idx, article in enumerate(articles):
                article_title = article["title"]
                article_body = article["body"]
                first_line = (
                    article_body.strip().split("\n", 1)[0].strip()
                    if article_body.strip()
                    else ""
                )
                speech_title = article_title.strip()
                speech_body = article_body
                if speech_title and first_line and speech_title == first_line:
                    speech_body = article_body.strip()[len(first_line) :].lstrip("\n ")
                # Translate to target language if needed
                if lang_code != "en":
                    try:
                        speech_title = translate_text(speech_title, lang_code)
                        speech_body = translate_text(speech_body, lang_code)
                    except RuntimeError as e:
                        logging.error(
                            "Halting processing for language '%s' due to translation failure: %s",
                            lang_code,
                            e,
                        )
                        typer.echo(
                            f"Halting processing for language '{lang_code}' due to translation failure: {e}",
                            err=True,
                        )
                        return
                # Chunk article body for TTS API limits
                article_chunks = chunk_text(speech_body)
                audio_segments = []
                voice_blacklist = set()
                for idx, chunk in enumerate(article_chunks):
                    chunk_to_speak = chunk
                    if lang_code != "en":
                        chunk_to_speak = translate_text(chunk, lang_code)
                    # Try all voices for this article/chunk, blacklisting failed ones
                    success = False
                    for try_voice in [voices_to_use[article_idx]] + [
                        v for v in voice_list if v != voices_to_use[article_idx]
                    ]:
                        if (
                            try_voice in voice_blacklist
                            or try_voice in BLACKLISTED_TTS_VOICES
                        ):
                            continue
                        ssml, _ = SSMLPreprocessor(lang_code=lang_code).generate_ssml(
                            title=speech_title,
                            body=chunk_to_speak,
                            voice_name=try_voice,
                            lang=lang_code,
                            style=lang_style,
                        )
                        speech_config = speechsdk.SpeechConfig(
                            subscription=AZURE_API_KEY, region=AZURE_REGION
                        )
                        speech_config.speech_synthesis_voice_name = try_voice
                        audio_segment = synthesize_audio(ssml, speech_config, try_voice)
                        if audio_segment:
                            audio_segments.append(audio_segment)
                            # Generated by Copilot: Always log the used voice for every chunk, language, and article for accessibility and traceability
                            logging.info(
                                "Used voice '%s' for chunk %d of article '%s' in %s (language: %s).",
                                try_voice,
                                idx,
                                speech_title,
                                docx_path,
                                lang_code,
                            )
                            success = True
                            break
                        else:
                            logging.error(
                                "TTS synthesis failed for voice %s on chunk %d of article '%s' in %s. Blacklisting this voice for this run.",
                                try_voice,
                                idx,
                                speech_title,
                                docx_path,
                            )
                            voice_blacklist.add(try_voice)
                            # Persistently blacklist this voice for future runs
                            if try_voice not in BLACKLISTED_TTS_VOICES:
                                try:
                                    import ast

                                    config_path = Path(__file__).parent / "config.py"
                                    with open(config_path, "r", encoding="utf-8") as f:
                                        lines = f.readlines()
                                    for i, line in enumerate(lines):
                                        if line.strip().startswith(
                                            "BLACKLISTED_TTS_VOICES"
                                        ):
                                            # Parse and update the list
                                            prefix = line.split("=")[0]
                                            current = ast.literal_eval(
                                                line.split("=", 1)[1].strip()
                                            )
                                            if try_voice not in current:
                                                current.append(try_voice)
                                                lines[i] = (
                                                    f"{prefix}= {current}  # Updated by pipeline on failure\n"
                                                )
                                                break
                                    with open(config_path, "w", encoding="utf-8") as f:
                                        f.writelines(lines)
                                    logging.critical(
                                        "Persistently blacklisted voice %s in config.py due to repeated TTS failure.",
                                        try_voice,
                                    )
                                except (
                                    OSError,
                                    IOError,
                                    ValueError,
                                    SyntaxError,
                                ) as persist_exc:
                                    logging.error(
                                        "Failed to persistently blacklist voice %s in config.py: %s",
                                        try_voice,
                                        persist_exc,
                                    )
                    if not success:
                        # Robust error: stop processing if any chunk fails
                        if chunk_to_speak.strip():
                            logging.critical(
                                "All voices failed for chunk %d of article '%s' in %s. Article has non-empty text. Halting processing for this language. Text: '%s'...",
                                idx,
                                speech_title,
                                docx_path,
                                chunk_to_speak[:120].replace("\n", " "),
                            )
                            typer.echo(
                                f"CRITICAL: All voices failed for chunk {idx} of article '{speech_title}' in {docx_path}. Article has non-empty text. Halting processing for this language. Text: '{chunk_to_speak[:120].replace('\n', ' ')}'...",
                                err=True,
                            )
                        else:
                            logging.critical(
                                "All voices failed for chunk %d of article '%s' in %s. Article text is empty. Halting processing for this language.",
                                idx,
                                speech_title,
                                docx_path,
                            )
                            typer.echo(
                                f"CRITICAL: All voices failed for chunk {idx} of article '{speech_title}' in {docx_path}. Article text is empty. Halting processing for this language.",
                                err=True,
                            )
                        # Clean up all output for this language (except English) if a failure occurs
                        if lang_code != "en":
                            lang_output_dir = OUTPUT_DIR / docx_path.stem
                            for subdir in ["speech", "text", "merged"]:
                                lang_dir = lang_output_dir / subdir / lang_code
                                if lang_dir.exists():
                                    try:
                                        shutil.rmtree(lang_dir)
                                        logging.critical(
                                            "Deleted output directory %s due to failure in language '%s'.",
                                            lang_dir,
                                            lang_code,
                                        )
                                    except (OSError, IOError) as cleanup_exc:
                                        logging.error(
                                            "Failed to delete output directory %s during cleanup: %s",
                                            lang_dir,
                                            cleanup_exc,
                                        )
                        return
                if audio_segments:
                    # Merge all audio segments for the article
                    final_audio = audio_segments[0]
                    for seg in audio_segments[1:]:
                        final_audio += seg
                    # Generate safe file name for output
                    safe_title = (
                        "".join(
                            c
                            for c in article_title
                            if c.isalnum() or c in (" ", "_", "-")
                        )
                        .strip()
                        .replace(" ", "_")
                    )
                    if not safe_title:
                        safe_title = docx_path.stem
                    # Prepare output directories for speech and text
                    speech_output_dir = (
                        OUTPUT_DIR / docx_path.stem / "speech" / lang_code
                    )
                    text_output_dir = OUTPUT_DIR / docx_path.stem / "text" / lang_code
                    speech_output_dir.mkdir(parents=True, exist_ok=True)
                    text_output_dir.mkdir(parents=True, exist_ok=True)
                    out_path = speech_output_dir / f"{safe_title}.mp3"
                    text_path = text_output_dir / f"{safe_title}.txt"
                    # Prevent writing to root-level language folder
                    if (
                        speech_output_dir == ENGLISH_DIR
                        or speech_output_dir == SPANISH_DIR
                    ):
                        logging.error(
                            "Attempted to write output to root-level language folder: %s. This is not allowed. Output should be grouped by document name.",
                            speech_output_dir,
                        )
                        typer.echo(
                            f"ERROR: Output path {speech_output_dir} is a root-level language folder. Please check output logic.",
                            err=True,
                        )
                    else:
                        logging.info(
                            "Output path for article '%s' is %s (grouped by document, speech/text, and language as expected)",
                            article_title,
                            out_path,
                        )
                    # Ensure unique file names if needed
                    base_safe_title = safe_title
                    unique_idx = 1
                    while out_path.exists() or text_path.exists():
                        safe_title = f"{base_safe_title}_{unique_idx}"
                        out_path = speech_output_dir / f"{safe_title}.mp3"
                        text_path = text_output_dir / f"{safe_title}.txt"
                        unique_idx += 1
                    try:
                        final_audio.export(out_path, format="mp3")
                        # Loudness normalization using ffmpeg loudnorm
                        norm_path = out_path.with_name(out_path.stem + "_norm.mp3")
                        loudnorm_args = [
                            "ffmpeg",
                            "-y",
                            "-i",
                            str(out_path),
                            "-af",
                            f"loudnorm=I={LOUDNORM_PARAMS['I']}:TP={LOUDNORM_PARAMS['TP']}:LRA={LOUDNORM_PARAMS['LRA']}:print_format={LOUDNORM_PARAMS['print_format']}",
                            str(norm_path),
                        ]
                        try:
                            # Run ffmpeg to normalize loudness of individual article audio file
                            subprocess.run(
                                loudnorm_args, check=True, capture_output=True
                            )
                            # Overwrite original article audio file with normalized version
                            norm_path.replace(
                                out_path
                            )  # Overwrite original with normalized
                            logging.info(
                                "Loudness normalized audio for article '%s' at %s",
                                article_title,
                                out_path,
                            )
                        except OSError as e:
                            # Log error if normalization fails, but continue pipeline
                            logging.error(
                                "Loudness normalization failed for %s: %s",
                                out_path,
                                e,
                            )
                        with open(text_path, "w", encoding="utf-8") as f:
                            f.write(f"{speech_title}\n\n{speech_body}\n")
                        logging.info(
                            "Exported text for article '%s' from %s to %s",
                            article_title,
                            docx_path,
                            text_path,
                        )
                    except OSError as e:
                        logging.error(
                            "Failed to export audio or text for article '%s' to %s or %s: %s",
                            article_title,
                            out_path,
                            text_path,
                            e,
                        )
                        typer.echo(
                            f"Failed to export audio or text for article '{article_title}' to {out_path} or {text_path}: {e}",
                            err=True,
                        )
                else:
                    # Improved logging for empty or skipped articles
                    if not article_body.strip():
                        logging.warning(
                            "Skipped article '%s' in %s: body text is empty.",
                            article_title,
                            docx_path,
                        )
                    else:
                        logging.error(
                            "No audio generated for article '%s' in %s (chunks: %d, body length: %d)",
                            article_title,
                            docx_path,
                            len(article_chunks),
                            len(article_body.strip()),
                        )
                    typer.echo(
                        f"No audio generated for article '{article_title}' in {docx_path}",
                        err=True,
                    )
            # After all per-article audio is generated, merge with cue if needed
            # Only insert cue if cue_sound is True and there are multiple articles (i.e., headings)
            if cue_sound and len(articles) > 1:
                try:
                    cue_path = Path("page_turn.mp3")
                    cue_audio = AudioSegment.from_file(str(cue_path), format="mp3")
                    # Collect all article audio segments
                    article_audio_paths = []
                    for article in articles:
                        safe_title = (
                            "".join(
                                c
                                for c in article["title"]
                                if c.isalnum() or c in (" ", "_", "-")
                            )
                            .strip()
                            .replace(" ", "_")
                        )
                        if not safe_title:
                            safe_title = docx_path.stem
                        speech_output_dir = (
                            OUTPUT_DIR / docx_path.stem / "speech" / lang_code
                        )
                        out_path = speech_output_dir / f"{safe_title}.mp3"
                        article_audio_paths.append(out_path)
                    # Merge with cue between articles
                    merged = None
                    for idx, path in enumerate(article_audio_paths):
                        seg = AudioSegment.from_file(str(path), format="mp3")
                        if merged is None:
                            merged = seg
                        else:
                            merged += cue_audio
                            merged += seg
                    # Save merged file to output dir for every language
                    merged_output_dir = (
                        OUTPUT_DIR / docx_path.stem / "merged" / lang_code
                    )
                    merged_output_dir.mkdir(parents=True, exist_ok=True)
                    merged_path = (
                        merged_output_dir / f"{docx_path.stem}_{lang_code}.mp3"
                    )
                    merged.export(str(merged_path), format="mp3")
                    # Prepare ffmpeg loudnorm arguments for merged output normalization
                    norm_merged_path = merged_path.with_name(
                        merged_path.stem + "_norm.mp3"
                    )
                    loudnorm_args = [
                        "ffmpeg",
                        "-y",
                        "-i",
                        str(merged_path),
                        "-af",
                        f"loudnorm=I={LOUDNORM_PARAMS['I']}:TP={LOUDNORM_PARAMS['TP']}:LRA={LOUDNORM_PARAMS['LRA']}:print_format={LOUDNORM_PARAMS['print_format']}",
                        str(norm_merged_path),
                    ]
                    try:
                        # Run ffmpeg to normalize loudness of merged audio file
                        subprocess.run(loudnorm_args, check=True, capture_output=True)
                        # Overwrite original merged file with normalized version
                        norm_merged_path.replace(merged_path)
                        logging.info(
                            "Loudness normalized merged audio for %s at %s",
                            docx_path,
                            merged_path,
                        )
                    except OSError as e:
                        # Log error if normalization fails, but continue pipeline
                        logging.error(
                            "Loudness normalization failed for merged file %s: %s",
                            merged_path,
                            e,
                        )
                except OSError as e:
                    logging.error(
                        "Failed to merge audio with cue sound for language %s: %s",
                        lang_code,
                        e,
                    )
                # No need to catch PackageNotFoundError here; only docx parsing can raise it
            else:
                if cue_sound and len(articles) > 1:
                    logging.error(
                        "Merged output was not created for language %s in %s",
                        lang_code,
                        docx_path,
                    )


# Entry point for CLI
if __name__ == "__main__":
    app()
