# Generated by Copilot
# Configuration file for storing constants and API strings

import os
from pathlib import Path  # Generated by Copilot

# Azure Speech API key for authentication
AZURE_API_KEY = os.getenv(
    "GITHUB_SECRET_AZURE_API_KEY", os.getenv("AZURE_API_KEY", "")
)
# Azure region for TTS service
AZURE_REGION = "westus"

# Azure Translator API key for translation support
AZURE_TRANSLATOR_KEY = os.getenv(
    "AZURE_TRANSLATOR_KEY", "YOUR_DEFAULT_TRANSLATOR_KEY_HERE"
)
# Azure Translator endpoint URL
AZURE_TRANSLATOR_ENDPOINT = "https://api.cognitive.microsofttranslator.com"
# Azure Translator region
AZURE_TRANSLATOR_REGION = "westus"  # Or your specific region

# File Paths
PAGE_CUE_PATH = "page_turn.mp3"

# Use pathlib for path manipulations
_config_file_dir = Path(__file__).resolve().parent
# Output directory for all generated audio and text files
OUTPUT_DIR = Path(
    "output_audio"
)  # Represents a relative path, consistent with original "output_audio" string

# Default Voice
DEFAULT_VOICE = "en-US-JennyNeural"

# Default speaking style for TTS
DEFAULT_STYLE = "newscast"

# Output directory for English language files
ENGLISH_DIR = OUTPUT_DIR / "en"
# Output directory for Spanish language files
SPANISH_DIR = OUTPUT_DIR / "es"

# Directory for data files (acronyms, publications, specialized terms)
# Defaults to the directory where the scripts are located.
DATA_DIR = _config_file_dir  # Use the Path object defined above

# Language-specific data files
ENGLISH_TERMS_FILE = "specialized_terms_en.json"
SPANISH_TERMS_FILE = (
    "specialized_terms_es.json"  # blank for now until mappings available
)

# Default Voices
DEFAULT_ENGLISH_VOICE = "en-US-JennyNeural"
DEFAULT_SPANISH_VOICE = (
    "es-ES-ElviraNeural"  # Well-rated female neural voice for Spanish
)

# Supported languages and their configuration (voice, etc.)
LANGUAGES = {
    "en": {
        "output_dir": ENGLISH_DIR,
        "voice": DEFAULT_ENGLISH_VOICE,
        "terms_file": ENGLISH_TERMS_FILE,
        "translator_locale": "en",
    },
    "es": {
        "output_dir": SPANISH_DIR,
        "voice": DEFAULT_SPANISH_VOICE,
        "terms_file": SPANISH_TERMS_FILE,
        "translator_locale": "es",
    },
}

# Default languages to process if none specified
DEFAULT_LANGUAGES = ["en", "es"]

# --- Accessibility/Audio: Default pause (ms) between articles in chapter marker file ---
CHAPTER_PAUSE_MS = 500  # Default pause duration in milliseconds between articles in chapter marker files.

# --- Accessibility/Audio: Default silence (ms) between spoken segments ---
SILENCE_LEN_MS = 300  # Default silence duration in milliseconds for pauses between audio segments. Adjust for pacing and accessibility.
# This value is used to insert pauses for screen reader and auditory clarity. Increase for longer pauses.

# --- Accessibility/Audio: Silence threshold in decibels for detecting silence in audio ---
SILENCE_THRESH_DB = (
    -40
)  # Default silence threshold in dB. Used to detect silent segments in audio for splitting or processing. Adjust for your environment and needs.
# This value helps ensure pauses are detected for screen reader and auditory clarity. Make less negative for noisier environments.

# --- Accessibility/Audio: Fade-in duration in milliseconds for audio segments ---
FADE_IN_MS = 0  # No fade-in effect. Set to 0 to disable fade-in for all audio segments. Adjust if a fade-in is needed for accessibility or user comfort.

# --- Accessibility/Audio: Fade-out duration in milliseconds for audio segments ---
FADE_OUT_MS = 0  # No fade-out effect. Set to 0 to disable fade-out for all audio segments. Adjust if a fade-out is needed for accessibility or user comfort.

# --- Accessibility/Audio: Loudness normalization parameters for ffmpeg loudnorm filter ---
LOUDNORM_PARAMS = {
    "I": -16,  # Target integrated loudness in LUFS (loud as possible for web/podcast, adjust to -14 for streaming)
    "TP": -1.5,  # True peak limit in dBTP (prevents clipping/distortion)
    "LRA": 11,  # Loudness range target
    "measured_I": None,  # Set by first pass, leave None for initial normalization
    "measured_TP": None,  # Set by first pass, leave None for initial normalization
    "measured_LRA": None,  # Set by first pass, leave None for initial normalization
    "measured_thresh": None,  # Set by first pass, leave None for initial normalization
    "offset": None,  # Set by first pass, leave None for initial normalization
    "linear": True,  # Use linear normalization
    "print_format": "json",  # Output format for ffmpeg filter
}
# These values ensure maximum loudness without clipping, following accessibility and broadcast standards.

# --- Voice Lists for Random Selection ---
# Populate these lists more comprehensively using the Azure TTS REST API or SDK
# For a full list, see: https://learn.microsoft.com/en-us/azure/ai-services/speech-service/language-support?tabs=tts

# List of available English neural voices for variety
AZURE_NEURAL_VOICES_EN_US = [
    "en-US-JennyNeural",
    "en-US-GuyNeural",
    "en-US-AriaNeural",
    "en-US-DavisNeural",
    "en-US-AmberNeural",
    "en-US-AshleyNeural",
    "en-US-BrandonNeural",
    "en-US-ChristopherNeural",
    "en-US-CoraNeural",
    "en-US-ElizabethNeural",
    "en-US-EricNeural",
    "en-US-JacobNeural",
    "en-US-JaneNeural",
    "en-US-JasonNeural",
    "en-US-MichelleNeural",
    "en-US-MonicaNeural",
    "en-US-NancyNeural",
    "en-US-RogerNeural",
    "en-US-SaraNeural",
    "en-US-SteffanNeural",
    "en-US-TonyNeural",
]

# List of available Spanish neural voices for variety
AZURE_NEURAL_VOICES_ES_LATAM = [
    # Mexico
    "es-MX-DaliaNeural",
    "es-MX-JorgeNeural",
    "es-MX-LorenzoNeural",
    "es-MX-BeatrizNeural",
    "es-MX-CandelaNeural",
    "es-MX-CarlotaNeural",
    "es-MX-CecilioNeural",
    "es-MX-GerardoNeural",
    "es-MX-LarissaNeural",
    "es-MX-LibertoNeural",
    "es-MX-LucianoNeural",
    "es-MX-NuriaNeural",
    "es-MX-PelayoNeural",
    "es-MX-RenataNeural",
    "es-MX-SaulNeural",
    "es-MX-TeoNeural",
    "es-MX-YagoNeural",
    # US
    "es-US-AlonsoNeural",
    "es-US-PalomaNeural",
    # Add other Latin American Spanish voices here (e.g., es-AR, es-CO, etc.)
]

# --- Persistent voice blacklist for TTS failures ---
# Add voices to this list to permanently exclude them from use in the pipeline.
# This list is updated at runtime if a voice fails, and can be reviewed or edited manually.
BLACKLISTED_TTS_VOICES = [
    "es-MX-LorenzoNeural",
    "es-MX-TeoNeural",
    "es-MX-SaulNeural",
]  # Updated by pipeline on failure
# Generated by Copilot

# --- Translation Retry/Timeout Parameters ---
TRANSLATION_MAX_RETRIES = 3  # Maximum number of translation attempts per text
TRANSLATION_RETRY_BACKOFF_BASE = 2  # Exponential backoff base (seconds)
TRANSLATION_RETRY_BACKOFF_MAX = 10  # Maximum backoff in seconds
TRANSLATION_TIMEOUT = 10  # Timeout for translation API requests (seconds)
# These values are used for robust translation logic: retry with exponential backoff, fallback, and accessible logging.
# Generated by Copilot

# Default for cleaning output directory before processing
CLEAN_OUTPUT_DEFAULT = True  # Default for --clean-output CLI switch
