"""
ssml_preprocessor.py

Preprocesses text and generates SSML for Azure TTS synthesis. Includes normalization, cleaning, and accessibility features.
Strictly conforms to WCAG 2.2 Level AA for accessibility (logging, error messages, etc).
Generated by Copilot
"""

import re
import json
import logging
from pathlib import Path
from config import DEFAULT_ENGLISH_VOICE as DEFAULT_VOICE, DATA_DIR


class SSMLPreprocessor:
    """Preprocesses text and generates SSML for Azure TTS synthesis.

    Attributes:
        data_dir (Path): Directory containing data files.
        acronym_dict (dict): Dictionary of acronyms and their pronunciations.
        publications_dict (dict): Dictionary of publication terms and their pronunciations.
        specialized_terms (dict): Dictionary of specialized terms and their pronunciations.
        time_patterns (list): List of regex patterns for time formatting.
        phone_pattern (re.Pattern): Regex pattern for phone numbers.
        email_pattern (re.Pattern): Regex pattern for email addresses.
    """

    def __init__(
        self,
        data_dir: Path = DATA_DIR,
        lang_code: str = "en",
    ):
        """Initialize the SSMLPreprocessor with the data directory and language-specific specialized terms.

        Args:
            data_dir (Path): Path to the data directory.
            lang_code (str): Language code (e.g., 'en', 'es').
        """
        self.data_dir = Path(data_dir)
        self.acronym_dict = self._load_json(self.data_dir / "acronyms.json")
        self.publications_dict = self._load_json(self.data_dir / "publications.json")
        terms_file = f"specialized_terms_{lang_code}.json"
        terms_path = self.data_dir / terms_file
        self.specialized_terms = self._load_json(terms_path)
        if not self.specialized_terms:
            logging.warning(
                "Specialized terms file '%s' missing or empty. No custom pronunciations will be applied.",
                terms_path,
            )
            self.specialized_terms = {}
        else:
            logging.info(
                "SSMLPreprocessor initialized. Loaded specialized terms from: %s",
                terms_path,
            )

        self.time_patterns = [
            (r"(\d{1,2}):(\d{2})\s*(am|pm|AM|PM)", self._format_time_range),
            (r"(\d{1,2})\s*(am|pm|AM|PM)", self._format_time_simple),
        ]

        self.phone_pattern = re.compile(r"\(?\d{3}\)?[-.\s]?\d{3}[-.\s]?\d{4}")
        self.email_pattern = re.compile(
            r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"
        )

    def _load_json(self, file_path: Path) -> dict:
        """Load data from a JSON file.

        Args:
            file_path (Path): Path to the JSON file.

        Returns:
            dict: Loaded data as a dictionary.
        """
        file_path = Path(file_path)
        if not file_path.exists():
            logging.warning("JSON file not found: %s", file_path)
            return {}
        with file_path.open("r", encoding="utf-8") as f:
            return json.load(f)

    def update_specialized_terms(self, lang_code: str) -> None:
        """Update the specialized terms dictionary by loading a new language-specific terms file.

        Args:
            lang_code (str): Language code (e.g., 'en', 'es').
        """
        file_path = self.data_dir / f"specialized_terms_{lang_code}.json"
        self.specialized_terms = self._load_json(file_path)
        if self.specialized_terms:
            logging.info(
                "SSMLPreprocessor updated specialized terms from: %s. Loaded %d terms.",
                file_path,
                len(self.specialized_terms),
            )
        else:
            logging.warning(
                "Specialized terms file '%s' missing or empty. No custom pronunciations will be applied.",
                file_path,
            )
            self.specialized_terms = {}

    def _format_time_range(self, match: re.Match) -> str:
        """Format time expressions with SSML.

        Args:
            match (re.Match): Regex match object.

        Returns:
            str: Formatted time string.
        """
        hour, minute = match.group(1), match.group(2)
        meridiem = match.group(3).lower() if match.group(3) else ""
        return f"{hour}:{minute}{meridiem}"

    def _format_time_simple(self, match: re.Match) -> str:
        """Format simple time expressions with SSML.

        Args:
            match (re.Match): Regex match object.

        Returns:
            str: Formatted time string.
        """
        hour, meridiem = match.group(1), match.group(2).lower()
        return f"{hour}:00{meridiem}"

    def _format_url(self, url: str) -> str:
        """Format URLs with SSML for normal pronunciation followed by detailed spelling.

        Args:
            url (str): URL string.

        Returns:
            str: Formatted URL string.
        """
        clean_url = re.sub(r"^https?://", "", url)
        if "<say-as" in clean_url or "<prosody" in clean_url:
            return url

        normal_speech = f'<say-as interpret-as="url">{clean_url}</say-as>'
        spelled_parts = []
        for char in clean_url:
            if char == ".":
                spelled_parts.append('<break time="150ms"/>period<break time="150ms"/>')
            elif char == "/":
                spelled_parts.append('<break time="100ms"/>slash<break time="100ms"/>')
            elif char == "-":
                spelled_parts.append('<break time="100ms"/>hyphen<break time="100ms"/>')
            elif char == "_":
                spelled_parts.append(
                    '<break time="100ms"/>underscore<break time="100ms"/>'
                )
            elif char == "@":
                spelled_parts.append('<break time="100ms"/>at<break time="100ms"/>')
            elif char.isalnum():
                spelled_parts.append(
                    f'<say-as interpret-as="characters">{char}</say-as>'
                )
            else:
                spelled_parts.append(
                    f'<say-as interpret-as="characters">{char}</say-as>'
                )

        detailed_spelling = '<break time="75ms"/>'.join(spelled_parts)
        return f'{normal_speech}<break time="500ms"/>{detailed_spelling}'

    def _format_phone_number(self, match: re.Match) -> str:
        """Format phone numbers with SSML for normal pronunciation.

        Args:
            match (re.Match): Regex match object.

        Returns:
            str: Formatted phone number string.
        """
        phone_number = match.group(0)
        if "<say-as" in phone_number or "<prosody" in phone_number:
            return phone_number
        return f'<say-as interpret-as="telephone">{phone_number}</say-as>'

    def _format_email(self, match: re.Match) -> str:
        """Format email addresses with SSML for natural pronunciation followed by detailed spelling.

        Args:
            match (re.Match): Regex match object.

        Returns:
            str: Formatted email address string.
        """
        email = match.group(0)
        if "<say-as" in email or "<prosody" in email:
            return email

        normal_speech = email
        spelled_parts = []
        for char in email:
            if char == ".":
                spelled_parts.append('<break time="150ms"/>period<break time="150ms"/>')
            elif char == "@":
                spelled_parts.append('<break time="150ms"/>at<break time="150ms"/>')
            elif char == "-":
                spelled_parts.append('<break time="100ms"/>hyphen<break time="100ms"/>')
            elif char == "_":
                spelled_parts.append(
                    '<break time="100ms"/>underscore<break time="100ms"/>'
                )
            elif char.isalnum():
                spelled_parts.append(
                    f'<say-as interpret-as="characters">{char}</say-as>'
                )
            else:
                spelled_parts.append(
                    f'<say-as interpret-as="characters">{char}</say-as>'
                )

        detailed_spelling = '<break time="75ms"/>'.join(spelled_parts)
        return f'{normal_speech}<break time="500ms"/>{detailed_spelling}'

    def _add_breaks(self, text: str) -> str:
        """Add appropriate breaks for improved rhythm and natural speech.

        Args:
            text (str): Input text.

        Returns:
            str: Text with added breaks.
        """
        text = re.sub(r"([.!?])\s+", r"\1 ", text)
        text = re.sub(r",\s+", r", ", text)
        text = re.sub(r"\s+-\s+", r" - ", text)
        return text

    def _handle_emphasis(self, text: str) -> str:
        """Add emphasis to certain phrases.

        Args:
            text (str): Input text.

        Returns:
            str: Text with added emphasis.
        """
        text = re.sub(
            r"^([^.]+)\.\s*$",
            r'<emphasis level="strong">\1</emphasis>.',
            text,
            flags=re.MULTILINE,
        )

        emphasis_phrases = [
            "Important:",
            "Note:",
            "Warning:",
            "Caution:",
            "Canceled:",
            "Updated:",
            "New Location:",
        ]
        for phrase in emphasis_phrases:
            text = text.replace(phrase, f'<emphasis level="strong">{phrase}</emphasis>')
        return text

    def _format_publications(self, text: str) -> str:
        """Ensure 'Vol.' and 'No.' are pronounced as 'Volume' and 'Number'.

        Args:
            text (str): Input text.

        Returns:
            str: Text with formatted publication terms.
        """
        text = re.sub(r"\bVol\.\s*(\d+)", r"Volume \1", text)
        text = re.sub(r"\bNo\.\s*(\d+)", r"Number \1", text)
        return text

    def _format_ordinal_numbers(self, text: str) -> str:
        """Remove ordinal number formatting as speech will handle it.

        Args:
            text (str): Input text.

        Returns:
            str: Text without ordinal number formatting.
        """
        return text

    def _normalize_resolution_number(self, text: str) -> str:
        """Normalize resolution numbers like 2025-02 to '2025 dash 2' for natural speech output.
        Generated by Copilot
        """

        def replacer(match):
            year = match.group(1)
            num = match.group(2)
            # Remove leading zero from number
            num_spoken = str(int(num))
            return f"{year} dash {num_spoken}"

        # Only match 4-digit year followed by dash and 1-3 digits (e.g., 2025-02, 2025-12, 2025-123)
        return re.sub(r"(20\d{2})-(\d{1,3})", replacer, text)

    def preprocess_text(
        self,
        text: str,
        voice_name: str = DEFAULT_VOICE,
        rate: float = 1.0,
        lang: str = "en-US",
        style: str = "newscast",
    ) -> str:
        """Apply comprehensive SSML preprocessing to text."""
        saved_tags = []

        def save_tag(match):
            saved_tags.append(match.group(0))
            return f"SAVED_TAG_{len(saved_tags)-1}"

        text = re.sub(r"<[^>]+>[^<]*</[^>]+>|<[^>]+/>", save_tag, text)
        text = text.replace('"', "")
        text = text.replace("&", "&amp;")
        text = text.replace("<", "&lt;")
        text = text.replace(">", "&gt;")
        text = text.replace('"', "&quot;")
        text = text.replace("'", "&apos;")

        for i, tag in enumerate(saved_tags):
            text = text.replace(f"SAVED_TAG_{i}", tag)

        # Normalize resolution numbers (e.g., 2025-02 -> 2025 dash 2)
        text = self._normalize_resolution_number(text)

        for term_dict in [self.acronym_dict, self.specialized_terms]:
            for term, pronunciation in term_dict.items():
                escaped_term = re.escape(term)
                pattern = r"(?i)\b" + escaped_term + r"\b"
                text = re.sub(pattern, pronunciation, text)

        text = self._format_publications(text)
        text = self._format_ordinal_numbers(text)
        text = self.email_pattern.sub(self._format_email, text)
        text = self.phone_pattern.sub(self._format_phone_number, text)

        url_pattern = r'https?://[^\s<>"]+|www\.[^\s<>"]+'
        potential_urls = re.findall(url_pattern, text)
        for url in potential_urls:
            if "<say-as" not in url and "<prosody" not in url:
                formatted_url = self._format_url(url)
                text = text.replace(url, formatted_url)

        for pattern, formatter in self.time_patterns:
            text = re.sub(pattern, formatter, text)

        text = self._handle_emphasis(text)
        text = self._add_breaks(text)

        style_element = ""
        if style and style.lower() != "none":
            style_element = f'<mstts:express-as style="{style}">'

        closing_style_element = ""
        if style and style.lower() != "none":
            closing_style_element = "</mstts:express-as>"

        ssml = f"""<speak version="1.0" xmlns="http://www.w3.org/2001/10/synthesis" xmlns:mstts="http://www.w3.org/2001/mstts" xml:lang="{lang}">
    <voice name="{voice_name}">
        {style_element} 
        <prosody rate="{rate}" pitch="+0%">
            {text}
        </prosody>
        {closing_style_element}
    </voice>
</speak>"""

        ssml = ssml.replace("&lt;", "<").replace("&gt;", ">")

        try:
            from xml.etree import ElementTree

            ElementTree.fromstring(ssml)
        except ElementTree.ParseError as exc:
            raise ValueError("Generated SSML has invalid structure.") from exc

        return ssml

    def generate_ssml(
        self,
        title: str,
        body: str,
        voice_name: str,
        lang: str,
        text_override: str = None,
        rate: float = 1.0,
        style: str = "newscast",
    ) -> tuple[str, str]:
        """
        Generate SSML for Azure TTS synthesis.
        - title: Article or section title (used for screen reader and navigation)
        - body: Main text content
        - voice_name: Azure neural voice to use
        - lang: Language code (e.g., 'en', 'es')
        - style: Speaking style (e.g., 'general', 'chat', etc.)
        Returns: (ssml_string, full_text_string)
        """
        if text_override:
            full_text = text_override
        else:
            full_text = f"{title}. {body}" if body else title

        ssml = self.preprocess_text(
            full_text, voice_name=voice_name, rate=rate, lang=lang, style=style
        )
        return ssml, full_text
