"""Generate QUILL's build-identity module from build/version.toml.

Run before each build (CI, local, packaging). Outputs:

- ``quill/_build_info.py`` - the runtime constants module the About
  dialog, crash reports, and support-info strings read from.
- ``build/build-info.txt`` - a plain-text copy for humans and support.

If the optional ``tomli`` backport is unavailable, the script falls back
to the Python 3.11+ stdlib ``tomllib``.

Usage::

    python tools/generate_build_info.py

Environment overrides:

- ``GITHUB_SHA`` - exact commit (GitHub Actions).
- ``GITHUB_RUN_NUMBER`` - build counter (GitHub Actions).
- ``QUILL_BUILD_NUMBER`` - local override for the build counter.

This script never raises on transient failures (missing git, no network).
It writes a generated module that records what it could and could not
determine.
"""

from __future__ import annotations

import datetime as dt
import os
import subprocess
import sys
from pathlib import Path

try:
    import tomllib  # pyright: ignore[reportMissingImports]
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 fallback
    sys.path.insert(0, str(Path(__file__).resolve().parent))
    import tomli as tomllib  # type: ignore[no-redef]

from quill.branding import APP_DISPLAY_NAME, APP_ORGANIZATION

ROOT = Path(__file__).resolve().parents[1]
VERSION_FILE = ROOT / "build" / "version.toml"
OUTPUT_FILE = ROOT / "quill" / "_build_info.py"
INFO_TXT_FILE = ROOT / "build" / "build-info.txt"


def run_git(args: list[str], default: str = "") -> str:
    """Run a git command and return stdout. Returns ``default`` on failure."""
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=ROOT,
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except Exception:
        return default


def pep440_version(base: str, channel: str, pre: int, build_number: str, date: str) -> str:
    """PEP 440 version string for the Python package metadata."""
    if channel == "stable":
        return base
    if channel == "alpha":
        return f"{base}a{pre}"
    if channel == "beta":
        return f"{base}b{pre}"
    if channel == "rc":
        return f"{base}rc{pre}"
    numeric_stamp = f"{date}{build_number}".replace(".", "")
    return f"{base}.dev{numeric_stamp}"


def display_version(base: str, channel: str, pre: int) -> str:
    """User-facing release label, e.g. '0.7.0 Beta 1' or '0.7.0'."""
    if channel == "stable":
        return base
    if channel == "alpha":
        return f"{base} Alpha {pre}"
    if channel == "beta":
        return f"{base} Beta {pre}"
    if channel == "rc":
        return f"{base} Release Candidate {pre}"
    return f"{base} Dev"


def main() -> int:
    if not VERSION_FILE.exists():
        print(f"ERROR: {VERSION_FILE} not found.", file=sys.stderr)
        return 1

    config = tomllib.loads(VERSION_FILE.read_text(encoding="utf-8"))

    product_name = str(config.get("product_name", APP_DISPLAY_NAME))
    publisher = str(config.get("publisher", APP_ORGANIZATION))
    website = str(config.get("website", "https://quillforall.org"))
    base = str(config["base_version"])
    channel = str(config.get("channel", "dev"))
    pre = int(config.get("prerelease_number", 0))

    now = dt.datetime.now(dt.UTC)
    build_date = now.strftime("%Y%m%d")
    build_date_pretty = now.strftime("%Y-%m-%d")
    build_time = now.strftime("%H:%M:%SZ")

    build_number = os.getenv("QUILL_BUILD_NUMBER") or os.getenv("GITHUB_RUN_NUMBER") or "0"
    git_sha_full = os.getenv("GITHUB_SHA") or run_git(["rev-parse", "HEAD"], "unknown")
    git_sha = git_sha_full[:7] if git_sha_full != "unknown" else "unknown"
    dirty = bool(run_git(["status", "--porcelain"], ""))

    build_stamp = f"{build_date}.{build_number}"
    nice_version = display_version(base, channel, pre)
    full_display = f"{product_name} {nice_version} build {build_stamp}"
    pep440 = pep440_version(base, channel, pre, build_number, build_date)

    OUTPUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_FILE.write_text(
        f"""# This file is generated by tools/generate_build_info.py. Do not edit by hand.
# Regenerate with: python tools/generate_build_info.py

PRODUCT_NAME = {product_name!r}
PUBLISHER = {publisher!r}
WEBSITE = {website!r}
BASE_VERSION = {base!r}
CHANNEL = {channel!r}
PRERELEASE_NUMBER = {pre!r}

DISPLAY_VERSION = {nice_version!r}
BUILD_STAMP = {build_stamp!r}
FULL_DISPLAY_VERSION = {full_display!r}

PEP440_VERSION = {pep440!r}
GIT_SHA = {git_sha!r}
GIT_SHA_FULL = {git_sha_full!r}
BUILD_DATE = {build_date_pretty!r}
BUILD_TIME = {build_time!r}
BUILD_NUMBER = {build_number!r}
DIRTY = {dirty!r}
""",
        encoding="utf-8",
    )

    INFO_TXT_FILE.parent.mkdir(parents=True, exist_ok=True)
    INFO_TXT_FILE.write_text(
        f"{full_display}\nPEP 440: {pep440}\nCommit: {git_sha_full}\nDirty: {dirty}\n",
        encoding="utf-8",
    )

    print(full_display)
    return 0


if __name__ == "__main__":
    sys.exit(main())
