"""Generate quill/_feedback_token.py, the bundled issues-only GitHub token.

Run before packaging (CI, local build). Reads QUILL_FEEDBACK_GITHUB_TOKEN
from the environment and writes it into a gitignored constant so ordinary
users (who have never configured a personal GitHub token) can still file a
bug report through the "Report a Bug" dialog. See
docs/superpowers/specs/2026-07-06-bundled-feedback-token-design.md.

By default this never fails: a missing env var just writes an empty token, so
dev checkouts, tests, and local test builds without the secret are unaffected.
Pass ``--require-token`` (which the release/beta packaging does) to make a
missing/empty token a hard error instead: shipping a distributable build with an
empty bundled token silently breaks "Report a Bug" for every user who never
configured a personal token, which is the worst build to have in the field (it
silences the channel that would tell us it is broken). A release build must fail
loudly rather than degrade to a quietly broken binary.

The token itself must be a fine-grained GitHub PAT scoped only to
Community-Access/quill with Issues: read/write and no other permission (see the
design doc for how to create one).

Usage::

    python tools/generate_feedback_token.py                 # lenient (dev)
    python tools/generate_feedback_token.py --require-token  # release/beta
"""

from __future__ import annotations

import argparse
import os
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_FILE = ROOT / "quill" / "_feedback_token.py"
ENV_VAR = "QUILL_FEEDBACK_GITHUB_TOKEN"


def write_module(token: str, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""# This file is generated by tools/generate_feedback_token.py. Do not edit by hand.
# Regenerate with: QUILL_FEEDBACK_GITHUB_TOKEN=<token> python tools/generate_feedback_token.py

BUNDLED_TOKEN = {token!r}
""",
        encoding="utf-8",
    )


def read_existing_token(output_path: Path) -> str:
    """Return the non-empty BUNDLED_TOKEN already written to *output_path*, or "".

    Used so a build with no ``QUILL_FEEDBACK_GITHUB_TOKEN`` in its environment
    does not clobber a working token that was set up earlier -- keeping the bug
    reporter consistent across repeated dev/test builds (you populate the token
    once and rebuilds preserve it).
    """
    if not output_path.is_file():
        return ""
    text = output_path.read_text("utf-8")
    match = re.search(r"^BUNDLED_TOKEN = (['\"])(.*)\1", text, re.MULTILINE)
    return match.group(2) if match else ""


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--require-token",
        action="store_true",
        help=(
            "Fail (exit 2) instead of writing an empty token when "
            f"{ENV_VAR} is unset. Release/beta/preview packaging passes this so a "
            "distributable build can never silently ship with a broken bug reporter."
        ),
    )
    args = parser.parse_args(argv)
    token = os.environ.get(ENV_VAR, "").strip()
    if not token and args.require_token:
        print(
            f"ERROR: {ENV_VAR} is not set, but --require-token was given.\n"
            "A release/beta build must bundle a working issues-only token so users "
            "who never configured a personal GitHub token can still Report a Bug.\n"
            "Set the secret in the build environment and re-run, or drop "
            "--require-token for a local test build (its bug reporter will be "
            "unavailable).",
            file=sys.stderr,
        )
        return 2
    if not token:
        # No token in the environment: keep any working token already bundled
        # rather than wiping it to empty, so a dev/test rebuild stays consistent
        # (the token is populated once, then preserved). A fresh env token always
        # wins below.
        existing = read_existing_token(OUTPUT_FILE)
        if existing:
            print(f"{ENV_VAR} not set; preserving the existing bundled token in {OUTPUT_FILE}.")
            return 0
    write_module(token, OUTPUT_FILE)
    if token:
        print(f"Wrote {OUTPUT_FILE} with a bundled token.")
    else:
        print(f"{ENV_VAR} not set; wrote {OUTPUT_FILE} with an empty token.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
