"""Generate quill/_feedback_token.py, the bundled issues-only GitHub token.

Run before packaging (CI, local build). Reads QUILL_FEEDBACK_GITHUB_TOKEN
from the environment and writes it into a gitignored constant so ordinary
users (who have never configured a personal GitHub token) can still file a
bug report through the "Report a Bug" dialog. See
docs/superpowers/specs/2026-07-06-bundled-feedback-token-design.md.

Unlike tools/generate_build_info.py, this never fails: a missing env var
just writes an empty token, so dev checkouts, tests, and CI runs without the
secret are unaffected. The token itself must be a fine-grained GitHub PAT
scoped only to Community-Access/quill with Issues: read/write and no other
permission (see the design doc for how to create one).

Usage::

    python tools/generate_feedback_token.py
"""

from __future__ import annotations

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_FILE = ROOT / "quill" / "_feedback_token.py"
ENV_VAR = "QUILL_FEEDBACK_GITHUB_TOKEN"


def write_module(token: str, output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        f"""# This file is generated by tools/generate_feedback_token.py. Do not edit by hand.
# Regenerate with: QUILL_FEEDBACK_GITHUB_TOKEN=<token> python tools/generate_feedback_token.py

BUNDLED_TOKEN = {token!r}
""",
        encoding="utf-8",
    )


def main() -> int:
    token = os.environ.get(ENV_VAR, "").strip()
    write_module(token, OUTPUT_FILE)
    if token:
        print(f"Wrote {OUTPUT_FILE} with a bundled token.")
    else:
        print(f"{ENV_VAR} not set; wrote {OUTPUT_FILE} with an empty token.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
